### ISSUE TITLE
Feature Add Config File Support for Configuring Consumer and Provider GUIs

### ISSUE THREAD

**Issue by wollooo** [wollooo/sdc11073#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature idea

 To streamline the setup process and improve usability, I propose adding support for configuration via a config file. This feature will allow users to predefine settings and parameters in a file, enabling automatic loading of configurations at startup.

### Alternatives

GUI Enhancements:
    Provider GUI: Load settings from the config file to populate fields automatically on startup. Add an option to refresh the GUI with config values or revert to defaults.
    Consumer GUI: Load settings from the config file to configure parameters like search interval and plot time window.

### Implementation idea

Config File Format: Use a standard format such as JSON or YAML for the config file. Both formats can be easily integrated using Python libraries.

Example config.yaml:

```
provider:
  adapter: "Ethernet"
  manufacturer: "Draeger"
  model_name: "TestDevice"
  model_version: "1.0"
  model_url: "http://www.draeger.com/model"
  firmware_version: "Version1"
  friendly_name: "TestDevice"
  initial_metric_value: 0.0
  active_determination_period: 1494554822450
  validity: "Vld"
  activation_state: "On"

consumer:
  search_interval: 10
  plot_time_window: 600
```

### Participation

- [ ] I am willing to submit a pull request to implement this feature.
