### ISSUE TITLE
feature: Add Configurable Data Types for Display in Consumer and Provision by Provider GUIs

### ISSUE THREAD

**Issue by wollooo** [wollooo/sdc11073#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature idea

Currently, the SDC Consumer and Provider GUIs simulate and display a fixed set of physiological data types (e.g., ECG, respiratory, and EMG signals). To make the application more flexible and aligned with various use cases, I propose adding a feature that allows users to configure which data types should be simulated by the provider and displayed by the consumer. This will enable users to customize the GUIs for specific presentations and demonstrations, selecting the most relevant data types for their needs.

User Interface Adjustments: Add a section in the GUI or command-line options to allow to select which data types to simulate and display. This can be a list or checkboxes for user convenience.

### Alternatives

Best Data for Presentation:

To provide a compelling and informative presentation, consider including the following types of simulated data:

    ECG (Electrocardiogram): Provides clear visual patterns of heart activity, which are easily recognizable and useful for demonstrating real-time physiological monitoring.
    Respiratory Signals: Useful for showing breathing patterns and detecting anomalies in respiratory activity.
    EMG (Electromyography): Demonstrates muscle activity, which can be useful for presentations related to muscle response and motor control.
    SpO2 (Oxygen Saturation): While not currently included, adding SpO2 can be valuable for presentations focused on blood oxygen levels.
    Blood Pressure: Simulating blood pressure readings can add depth to presentations involving cardiovascular health monitoring.

### Implementation idea

Config File Extensions: Extend the config file (as described in a previous feature request) to include options for selecting data types for both the provider and consumer.

Example config.yaml

```
provider:
  adapter: "Ethernet"
  manufacturer: "Draeger"
  model_name: "TestDevice"
  model_version: "1.0"
  model_url: "http://www.draeger.com/model"
  firmware_version: "Version1"
  friendly_name: "TestDevice"
  initial_metric_value: 0.0
  active_determination_period: 1494554822450
  validity: "Vld"
  activation_state: "On"
  data_types: ["ECG", "Respiratory", "EMG"]  # New field for data types

consumer:
  search_interval: 10
  plot_time_window: 600
  display_data_types: ["ECG", "Respiratory", "EMG"]  # New field for display data types
```

### Participation

- [ ] I am willing to submit a pull request to implement this feature.
